//19 folder ek
export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL' 

//update ekt
export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_RESET = 'UPDATE_EMPLOYEE_RESET'
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL' 

export const EMPLOYEE_DETAILS_REQUEST = 'EMPLOYEE_DETAILS_REQUEST'
export const EMPLOYEE_DETAILS_SUCCESS = 'EMPLOYEE_DETAILS_SUCCESS'
export const EMPLOYEE_DETAILS_FAIL = 'EMPLOYEE_DETAILS_FAIL' 

//delete
export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_RESET = 'DELETE_EMPLOYEE_RESET'
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL' 


export const NEW_EMPLOYEE_REQUEST = 'NEW_EMPLOYEE_REQUEST'
export const NEW_EMPLOYEE_SUCCESS = 'NEW_EMPLOYEE_SUCCESS'
//export const NEW_EMPLOYEE_RESET = 'NEW_EMPLOYEE_RESET'
export const NEW_EMPLOYEE_FAIL = 'NEW_EMPLOYEE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'