export const ALL_FEEDBACKS_REQUEST = 'ALL_FEEDBACKS_REQUEST'
export const ALL_FEEDBACKS_SUCCESS = 'ALL_FEEDBACKS_SUCCESS'
export const ALL_FEEDBACKS_FAIL = 'ALL_FEEDBACKS_FAIL'

export const FEEDBACK_CREATE_REQUEST = 'FEEDBACK_CREATE_REQUEST'
export const FEEDBACK_CREATE_SUCCESS = 'FEEDBACK_CREATE_SUCCESS'
export const FEEDBACK_CREATE_FAIL = 'FEEDBACK_CREATE_FAIL'
export const FEEDBACK_CREATE_RESET = 'FEEDBACK_CREATE_RESET'

export const DELETE_ADMIN_FEEDBACK_REQUEST = 'DELETE__ADMIN_FEEDBACK_REQUEST'
export const DELETE_ADMIN_FEEDBACK_SUCCESS = 'DELETE__ADMIN_FEEDBACK_SUCCESS'
export const DELETE_ADMIN_FEEDBACK_RESET = 'DELETE__ADMIN_FEEDBACK_RESET'
export const DELETE_ADMIN_FEEDBACK_FAIL = 'DELETE__ADMIN_FEEDBACK_FAIL'

export const ADMIN_FEEDBACK_REQUEST = 'ADMIN_FEEDBACK_REQUEST'
export const ADMIN_FEEDBACK_SUCCESS = 'ADMIN_FEEDBACK_SUCCESS'
export const ADMIN_FEEDBACK_FAIL = 'ADMIN_FEEDBACK_FAIL'

export const CUSTOMER_FEEDBACKS_REQUEST = 'CUSTOMER_FEEDBACKS_REQUEST'
export const CUSTOMER_FEEDBACKS_SUCCESS = 'CUSTOMER_FEEDBACKS_SUCCESS'
export const CUSTOMER_FEEDBACKS_FAIL = 'CUSTOMER_FEEDBACKS_FAIL'

export const CUSTOMER_FEEDBACK_SINGLE_REQUEST = 'CUSTOMER_FEEDBACK_SINGLE_REQUEST'
export const CUSTOMER_FEEDBACK_SINGLE_SUCCESS = 'CUSTOMER_FEEDBACK_SINGLE_SUCCESS'
export const CUSTOMER_FEEDBACK_SINGLE_FAIL = 'CUSTOMER_FEEDBACK_SINGLE_FAIL'



export const CUSTOMER_DELETE_FEEDBACKS_REQUEST = 'CUSTOMER_FEEDBACKS_REQUEST'
export const CUSTOMER_DELETE_FEEDBACKS_SUCCESS = 'CUSTOMER_FEEDBACKS_SUCCESS'
export const CUSTOMER_DELETE_FEEDBACKS_FAIL = 'CUSTOMER_FEEDBACKS_FAIL'
export const CUSTOMER_DELETE_FEEDBACKS_RESET = 'CUSTOMER_DELETE_FEEDBACKS_RESET'

export const UPDATE_FEEDBACKS_REQUEST = 'UPDATE_FEEDBACKS_REQUEST'
export const UPDATE_FEEDBACKS_SUCCESS = 'UPDATE_FEEDBACKS_SUCCESS'
export const UPDATE_FEEDBACKS_FAIL = 'UPDATE_FEEDBACKS_FAIL'
export const UPDATE_FEEDBACKS_RESET = 'UPDATE_FEEDBACKS_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'